# Generated by Django 5.0.6 on 2024-05-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
    ]
