# Generated by Django 5.0.6 on 2024-05-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_app', '0006_rename_total_price_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('retailer', 'Retailer')], max_length=20),
        ),
    ]
